language: java

jdk:
  - oraclejdk8


branches:
  only:
    - master

before_install:
  - cd challenges/lovely_lucky_lambs/
  - wget 'http://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar'
#  - gradle check
#  - ./gradlew check
